######################
# Threads to use
######################
THREADS: 5

######################
# Database information
######################
DATABASE:
    type: 'mysql'
    mysql:
        user: 'indexit'
        password: 'indexit'
        host: '127.0.0.1'
        database: 'indexit'
        port: 3306
    sqlite:
        name: 'index'

######################
# Github api tokens
######################
GITHUB_TOKENS:
    - "1234"

######################
# Files/Folders
######################
FILES:
    blacklisted_dirs:
        - 'git'
        - '.git'
        - 'tests'
        - 'test'
    blacklisted_extensions:
        - '.exe'
        - '.png'
        - '.jpg'
        - '.zip'
        - '.rar'