######################
# Threads to use
######################
THREADS: 50

######################
# Database information
######################
DATABASE:
    name: 'harvested'

######################
# Github api tokens
######################
GITHUB_TOKENS:
    - "1234"

######################
# Files/Folders
######################
FILES:
    blacklisted_dirs:
        - 'git'
        - '.git'
        - 'tests'
        - 'test'
    blacklisted_extensions:
        - '.exe'
        - '.png'
        - '.jpg'
        - '.zip'
        - '.rar'